### ISSUE TITLE
Peer-to-peer code review (2021-11-11)

### ISSUE THREAD

**Issue by piero-vic** [micheaol/Leaderboard-project#3]
# Peer-to-peer code review
## Things to highlight
- Nice use of gitflow.
- Good use of modular JavaScript.
## Things that may be good to change
- I think you could simplify the `getForm` function by using async and wait. Just like you did with `fetchUser` function.
https://github.com/micheaol/Leaderboard-project/blob/cc2b4235610e91639284ad282574d76b9c4d421c/src/formdata.js#L10-L38
- You could implement this section using and html string. Just like you did in `home.js`.
https://github.com/micheaol/Leaderboard-project/blob/cc2b4235610e91639284ad282574d76b9c4d421c/src/formdata.js#L49-L60

**Comment by AlexRS90** [comment]
# Highlights
- Added a footer
- Added a confirmation message when the user submit a new score

# Suggestions
- I think you can avoid that the end-user sending empty data just adding <code>required</code> in your input text:

https://github.com/micheaol/Leaderboard-project/blob/cc2b4235610e91639284ad282574d76b9c4d421c/src/home.js#L23-L24

What do you think?
